version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_UID: 1000
                USER_GID: 1000
        ports:
            - 8090:8080
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
        env_file:
            - .env.locals
